SourceCode/Project3/Project3/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project3.Models;

namespace Project3.Controllers
{
    [Authorize(Roles = "ADMIN")]   
    
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<IActionResult> InsurancePlans()
        {
            var insurancePlans = await _context.InsurancePlans.Include(i => i.InsuranceType).ToListAsync();
            return insurancePlans != null ?
                          View(insurancePlans) :
                          Problem("Entity set 'ApplicationDbContext.InsurancePlans'  is null.");
        }
        public async Task<IActionResult> Users()
        {
            var users = await _context.Users.ToListAsync();
            return users != null ? 
                View(users) :
                Problem("Entity set 'ApplicationDbContext.Users'  is null.");
        }
        public async Task<IActionResult> Policies()
        {
            var policies = await _context.Policies.Include(p => p.InsurancePlan).Include(p => p.User).OrderByDescending(p => p.UpdatedDate).ToListAsync();
            return policies != null ?
                          View(policies) :
                          Problem("Entity set 'ApplicationDbContext.Policies'  is null.");
        }
            }
}

SourceCode/Project3/Project3/Controllers/AuthsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Project3.Models;
using Project3.ViewModels;
using System.Text;

namespace Project3.Controllers
{
    [AllowAnonymous]
    public class AuthsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ILogger<AuthsController> _logger;
        private readonly RoleManager<Role> _roleManager;

        public AuthsController(UserManager<User> userManager, SignInManager<User> signInManager, ILogger<AuthsController> logger, RoleManager<Role> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View("Login");
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            User user = new User
            {
                UserName = model.UserName,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                Address = model.Address,
                Gender = model.Gender,
                Fullname = model.FullName,
                DateOfBirth = model.DateOfBirth
            };
            var passwordHasher = new PasswordHasher<User>();
            string passwordHashed = passwordHasher.HashPassword(user, model.Password);
            IdentityResult result = await _userManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View(model);

            }
            await _userManager.AddToRoleAsync(user, Roles.USER.ToString());
            _logger.LogInformation("Create account success");
            return RedirectToAction(nameof(Login));
        }
        public IActionResult Login(string returnUrl = "")
        {
            var model = new LoginViewModel { ReturnUrl = returnUrl };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            User? user = await _userManager.FindByNameAsync(model.UserName);
            if (user == null)
            {
                ModelState.AddModelError("", "Invalid login attempt");
                return View(model);
            }
            var result = await _signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, true);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Invalid login attempt");
                return View(model);
            }
            if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                {
                    return Redirect(model.ReturnUrl);
            }
            ModelState.AddModelError("", "Invalid login attempt");
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult UpdateProfileInfo()
        {
            return View();
        }
    }

}

SourceCode/Project3/Project3/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Insure - Insurance HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="~/images/favicon.ico" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Poppins:wght@600;700&display=swap"
          rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" />
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="~/css/styles.css" rel="stylesheet" />
    @RenderSection("head", false)
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->
    <!-- Topbar Start -->
    <div class="container-fluid bg-dark text-white-50 py-2 px-0 d-none d-lg-block">
        <div class="row gx-0 align-items-center">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <small class="fa fa-phone-alt me-2"></small>
                    <small>+012 345 6789</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <small class="far fa-envelope-open me-2"></small>
                    <small>info@example.com</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <small class="far fa-clock me-2"></small>
                    <small>Mon - Fri : 09 AM - 09 PM</small>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center">
                    <a class="text-white-50 ms-4" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="text-white-50 ms-4" href=""><i class="fab fa-twitter"></i></a>
                    <a class="text-white-50 ms-4" href=""><i class="fab fa-linkedin-in"></i></a>
                    <a class="text-white-50 ms-4" href=""><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center">
            <h1 class="m-0">
                <img class="img-fluid me-3" src="~/images/icon/icon-02-primary.png" alt="" />Insure
            </h1>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav mx-auto bg-light rounded pe-4 py-3 py-lg-0">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link @(ViewBag.CurrentPage == "home" ? "active" : "")">Home</a>
                <a asp-controller="Home" asp-action="AboutUs" class="nav-item nav-link @(ViewBag.CurrentPage == "aboutus" ? "active" : "")">About Us</a>
                <a asp-controller="InsuranceTypes" asp-action="Index" class="nav-item nav-link @(ViewBag.CurrentPage == "ourservices" ? "active" : "")">Our Services</a>
                <a asp-controller="Home" asp-action="Features" class="nav-item nav-link @(ViewBag.CurrentPage == "features" ? "active" : "")">Features</a>
                <a asp-controller="Home" asp-action="Loan" class="nav-item nav-link @(ViewBag.CurrentPage == "loan" ? "active" : "")">Loan</a>
                <a asp-controller="Home" asp-action="ContactUs" class="nav-item nav-link @(ViewBag.CurrentPage == "contactus" ? "active" : "")">Contact Us</a>
            </div>
        </div>
        @if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            @if (User.IsInRole("ADMIN"))
            {
                <a asp-controller="Admins" asp-action="Index" class="btn btn-primary px-3 d-none d-lg-block" style="margin-right: 10px;">Admin</a>
            }
            else
            {
                <a asp-controller="Users" asp-action="Index" class="btn btn-primary px-3 d-none d-lg-block" style="margin-right: 10px;">User</a>
            }
            <a asp-controller="Auths" asp-action="Logout" class="btn btn-danger px-3 d-none d-lg-block" style="margin-right: 10px;">Logout</a>
        }
        else
        {
            <a asp-controller="Auths" asp-action="Register" class="btn btn-primary px-3 d-none d-lg-block" style="margin-right: 10px;">Sign Up</a>
            <a asp-controller="Auths" asp-action="Login" class="btn btn-primary px-3 d-none d-lg-block">Sign In</a>
        }
    </nav>
    <!-- Navbar End -->
    @RenderBody()
    <!-- Footer Start -->
    <div class="container-fluid bg-dark footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h1 class="text-white mb-4">
                        <img class="img-fluid me-3" src="~/images/icon/icon-02-light.png" alt="" />Insure
                    </h1>
                    <p>
                        Preparing you for life's what-ifs: Insurance that offers security and reassurance
                    </p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square me-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square me-1" href="https://www.facebook.com/bachtran9x6"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square me-1" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square me-0" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-light mb-4">Address</h5>
                    <p>
                        <i class="fa fa-map-marker-alt me-3"></i>54 Le Thanh Nghi, Ha Noi
                    </p>
                    <p><i class="fa fa-phone-alt me-3"></i>0962495730</p>
                    <p><i class="fa fa-envelope me-3"></i>bachtran9x6@gmail.com</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-light mb-4">Quick Links</h5>
                    <a class="btn btn-link" asp-controller="Home" asp-action="AboutUs">About Us</a>
                    <a class="btn btn-link" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                    <a class="btn btn-link" asp-controller="InsuranceTypes" asp-action="Index">Our Services</a>
                    <a class="btn btn-link" asp-controller="Home" asp-action="TeamMember">Team Member</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-light mb-4">Newsletter</h5>
                    <div class="position-relative mx-auto" style="max-width: 400px">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email" />
                        <button type="button" class="btn btn-secondary py-2 position-absolute top-0 end-0 mt-2 me-2">
                            SignUp
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", false)
</body>

</html>

SourceCode/Project3/Project3/Views/Shared/_UserLayout.cshtml
@model Project3.Models.User
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Insurance Admin</title>
    <!-- loader-->
    <link href="~/assets/css/pace.min.css" rel="stylesheet" />
    @*<script src="~/assets/js/pace.min.js"></script>*@
    <!--favicon-->
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon">
    <!-- Vector CSS -->
    <link href="~/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- simplebar CSS-->
    <link href="~/assets/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
    <!-- Bootstrap core CSS-->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="~/assets/css/animate.css" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Sidebar CSS-->
    <link href="~/assets/css/sidebar-menu.css" rel="stylesheet" />
    <!-- Custom Style-->
    <link href="~/assets/css/app-style.css" rel="stylesheet" />

</head>
<body class="bg-theme bg-theme1">

    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/assets/images/logo-icon.png" class="logo-icon" alt="logo icon">
                    <h5 class="logo-text">User Managerment</h5>
                </a>
            </div>
            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">MAIN NAVIGATION</li>
                <li>
                    <a>
                        <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>



                <li>
                    <a >
                        <i class="zmdi zmdi-format-list-bulleted"></i> <span>Profile</span>
                    </a>
                </li>
            </ul>

        </div>
        <!--End sidebar-wrapper-->
        <!--Start topbar header-->
        <header class="topbar-nav">
            <nav class="navbar navbar-expand fixed-top">
                <ul class="navbar-nav mr-auto align-items-center">
                    <li class="nav-item">
                        <a class="nav-link toggle-menu" href="javascript:void();">
                            <i class="icon-menu menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form class="search-bar">
                            <input type="text" class="form-control" placeholder="Enter keywords">
                            <a href="javascript:void();"><i class="icon-magnifier"></i></a>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav align-items-center right-nav-link">
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                            <i class="fa fa-envelope-open-o"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                            <i class="fa fa-bell-o"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
                            <span class="user-profile"><img src="https://thptkesat.edu.vn/wp-content/uploads/2023/01/1672993433_400_45-Avatar-Trang-Xoa-Cute-Dep-Cho-FB-Nam-Nu.jpg" class="img-circle" alt="user avatar"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item user-details">
                                <a href="javaScript:void();">
                                    <div class="media">
                                        <div class="avatar"><img class="align-self-start mr-3" src="https://thptkesat.edu.vn/wp-content/uploads/2023/01/1672993433_400_45-Avatar-Trang-Xoa-Cute-Dep-Cho-FB-Nam-Nu.jpg" alt="user avatar"></div>
                                        <div class="media-body">
                                            <h6 class="mt-2 user-title">@Model.Fullname</h6>
                                            <p class="user-subtitle">@Model.Email</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-envelope mr-2"></i> Inbox</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-settings mr-2"></i> Setting</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><a asp-controller="Auths" asp-action="Logout"><i class="icon-power mr-2"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </header>
        <!--End topbar header-->

        <div class="clearfix"></div>

        @RenderBody()
    </div>
    <!--End Row-->
    <!--End Dashboard Content-->
    <!--start overlay-->
    <div class="overlay toggle-menu"></div>
    <!--end overlay-->
    <!--End content-wrapper-->
    <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
    <!--Start footer-->
    <!--End footer-->
    <!--start color switcher-->
    <div class="right-sidebar">
        <div class="switcher-icon">
            <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
        </div>
        <div class="right-sidebar-content">

            <p class="mb-0">Gaussion Texture</p>
            <hr>

            <ul class="switcher">
                <li id="theme1"></li>
                <li id="theme2"></li>
                <li id="theme3"></li>
                <li id="theme4"></li>
                <li id="theme5"></li>
                <li id="theme6"></li>
            </ul>

            <p class="mb-0">Gradient Background</p>
            <hr>

            <ul class="switcher">
                <li id="theme7"></li>
                <li id="theme8"></li>
                <li id="theme9"></li>
                <li id="theme10"></li>
                <li id="theme11"></li>
                <li id="theme12"></li>
                <li id="theme13"></li>
                <li id="theme14"></li>
                <li id="theme15"></li>
            </ul>

        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- simplebar js -->
    <script src="~/assets/plugins/simplebar/js/simplebar.js"></script>
    <!-- sidebar-menu js -->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <!-- loader scripts -->
    <script src="~/assets/js/jquery.loading-indicator.js"></script>
    <!-- Custom scripts -->
    <script src="~/assets/js/app-script.js"></script>
    <!-- Chart js -->

    <script src="~/assets/plugins/Chart.js/Chart.min.js"></script>

    <!-- Index js -->
    <script src="~/assets/js/index.js"></script>


</body>
</html>